### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by 1127** [aidanamavi/nc-dns-updater#3]
Maybe it is obvious to everyone but me but how do you install this on a mac? Can you please add some instructions to the ReadMe?

**Comment by mozeryansky** [comment]
Download and open the workspace in Xcode. Then run the scheme. However, I could not get it to work on macos 10.14: https://github.com/aidanamavi/nc-dns-updater/issues/4

**Comment by sanctimon** [comment]
Does this work in Catalina on Xcode 11.7?

**Comment by mozeryansky** [comment]
@sanctimon What happens you run it in Catalina using Xcode 11.7?
